F1WebApp_CodeFirstSeededDb/Models/Driver.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace F1WebApp_CodeFirstSeededDb.Models
{
    public class Driver
    {
        [Key]
        public int DriverID { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Range(0.0, 100)]
        public int Age { get; set; }
        public string Country { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DebutYear { get; set; }
        [DisplayFormat(NullDisplayText = "Still Driving")]
        public DateTime? LastYear { get; set; }
        [Display(Name = "Full Name")]
        public string FullName
        {
            get { return FirstName + ' ' + LastName; }
        }
        //Adding foreign key constraints
        public virtual ICollection<Car> Cars { get; set; }
    }
}

F1WebApp_CodeFirstSeededDb/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using F1WebApp_CodeFirstSeededDb.DAL;
using F1WebApp_CodeFirstSeededDb.Models;

namespace F1WebApp_CodeFirstSeededDb.Controllers
{
    public class DriverController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Driver
        public ActionResult Index()
        {
            return View(db.Drivers.ToList());
        }

        // GET: Driver/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // GET: Driver/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Driver/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DriverID,FirstName,LastName,Age,Country,DebutYear,LastYear")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                db.Drivers.Add(driver);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(driver);
        }

        // GET: Driver/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // POST: Driver/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DriverID,FirstName,LastName,Age,Country,DebutYear,LastYear")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                db.Entry(driver).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(driver);
        }

        // GET: Driver/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // POST: Driver/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Driver driver = db.Drivers.Find(id);
            db.Drivers.Remove(driver);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

F1WebApp_CodeFirstSeededDb/Views/Driver/Create.cshtml
@model F1WebApp_CodeFirstSeededDb.Models.Driver

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Driver</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DebutYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DebutYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DebutYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

F1WebApp_CodeFirstSeededDb/Views/Driver/Delete.cshtml
@model F1WebApp_CodeFirstSeededDb.Models.Driver

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Driver</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DebutYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DebutYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastYear)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

F1WebApp_CodeFirstSeededDb/Views/Driver/Details.cshtml
@model F1WebApp_CodeFirstSeededDb.Models.Driver

@{
    ViewBag.Title = $"{@Model.FullName}";
    string imagePath = $"../../Images/{Model.DriverID}.png";
}
<style>
    #pp {
        max-height: 300px;
        border:3px solid #222;
        background: #999;
    }
    .details {
        padding-left: 15%;
        padding-right: 15%;
        font-size: 20px;
    }
    body {
        background: #444;
        color: white;
    }
</style>
<body>
    <h2>@ViewBag.Title</h2>

    <div>
        <h4>Driver</h4>
        <hr />
        <div class="container">
            <div class="col-lg-7 details">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.FullName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FullName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Age)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Age)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Country)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Country)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DebutYear)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DebutYear)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.LastYear)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.LastYear)
                    </dd>
                    @foreach (var car in Model.Cars)
                    {
                        <dd>
                            @car.Name
                        </dd>
                    }
                </dl>
            </div>
            <div class="col-lg-5">
                <img src=@imagePath id="pp" />
            </div>
        </div>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.DriverID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>

F1WebApp_CodeFirstSeededDb/Views/Driver/Edit.cshtml
@model F1WebApp_CodeFirstSeededDb.Models.Driver

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Driver</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DriverID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DebutYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DebutYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DebutYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

F1WebApp_CodeFirstSeededDb/Views/Driver/Index.cshtml
@model IEnumerable<F1WebApp_CodeFirstSeededDb.Models.Driver>

@{
    ViewBag.Title = "Index";
    string imagePath = "";
}

<head>
    <style>
        @@font-face {
            font-family: 'f1';
            src: url('../../Formula1-Regular.ttf');
        }
        body > * {
            background: #555;
        }
        .imageCont{
            overflow: hidden;
        }
        .pp {
            background: #EEE;
            max-width: 100%;
            transition: all 200ms ease-in-out;
        }
        .pp:hover {
            background: #777;
            transform: scale(1.1);
        }
        .card-title {
            font-weight: bold;
            font-size: 1.1em;
        }
        .card-header {
            background: #666;
            padding: 5px;
            text-align: center;
            color: white;
        }
        .card-body {
            background: crimson;
            color: white;
            font-weight: 800;
            text-align: center;
        }
        .card {
            background: #555;
            color: black;
            font-family: f1;
        }
        .row {
            display: flex;
            flex-direction:row;
            flex-wrap: wrap;
        }
    </style>
</head>
<body>
    <h2>@ViewBag.Title</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                imagePath = $"../../Images/{item.DriverID}.png";

                <div class="card col-lg-4">
                    <div class="card-header">
                        <h5 class="card-title">@item.FullName</h5>
                    </div>
                    <div class="imageCont">
                         <a href='@Url.Action($"Details/{item.DriverID}", "Driver")'><img src=@imagePath class="card-img-top pp" alt="..."></a>
                    </div>
                    <div class="card-body">
                        <p>
                            @Html.DisplayFor(modelItem => item.Age)
                        </p>
                        <p>
                            @Html.DisplayFor(modelItem => item.Country)
                        </p>
                        <p>
                            @Html.DisplayFor(modelItem => item.DebutYear)
                        </p>
                        <p>
                            @Html.DisplayFor(modelItem => item.LastYear)
                        </p>
                        <p>
                            @Html.ActionLink("Edit", "Edit", new { id = item.DriverID }) |
                            @Html.ActionLink("Details", "Details", new { id = item.DriverID }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.DriverID })
                        </p>
                    </div>
                </div>
            }
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Age)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Country)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DebutYear)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastYear)
                </th>
                <th></th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DebutYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastYear)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.DriverID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.DriverID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.DriverID })
                </td>
            </tr>
        }
    </table>

</body>